{
 "title": "Flink and Pravega Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "deploymentId", "query": "label_values(deploymentId)" }
  ]
 },
 "panels": [
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Segments",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "segment_num" }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Records/s" }
   ],
   "targets": [
    {
     "expr": "sum by (job_id) (flink_taskmanager_job_task_numRecordsOutPerSecond)/2",
     "legendFormat": "{{job_id}}"
    }
   ]
  },
  {
   "title": "Pravega Unread Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (job_id) (flink_taskmanager_job_task_operator_PravegaReader_readerGroup_unreadBytes)"
    }
   ]
  },
  {
   "title": "Task Managers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_numRegisteredTaskManagers{host=\"flink_jobmanager\"}",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "flink_jobmanager_numRegisteredTaskManagers{host=\"flink_jobmanager_comparsion\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "TaskManager CPU Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_CPU_Load",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Last Checkpoint Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_job_lastCheckpointDuration{deploymentId=\"$deploymentId\"}",
     "legendFormat": "Job {{job_id}}"
    }
   ]
  },
  { "title": "JVM Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Flink Master Heap Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Used{deploymentId=\"$deploymentId\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Taskmanager Heap Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Used{deploymentId=\"$deploymentId\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}