version: "2.1"
services:
  pravega:
    image: fyang86/pravega:0.10.1-65df3fbd-set-published-ip
    ports:
      - "9090:9090"
      - "12345:12345"
    command: standalone
    healthcheck:
      test: grep -F "Controller Services started successfully." standalone.log
    environment:
      HOST_IP: pravega

  mysql:
    image: thekingofcity/pravega-cdc-demo-mysql:0.1
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dbz
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD

  datagen:
    image: thekingofcity/pravega-cdc-demo-datagen:0.2
    depends_on:
      pravega:
        condition: service_healthy
      mysql:
        condition: service_healthy
      flink-jobmanager:
        condition: service_started
    healthcheck:
      test: grep -F "Scope and streams are created." log
    environment:
      - mysql_password=dbz

  debezium:
    image: thekingofcity/pravega-cdc-demo-debezium:0.1
    depends_on:
      pravega:
        condition: service_healthy
      mysql:
        condition: service_healthy
      datagen:
        condition: service_healthy
      flink-jobmanager:
        condition: service_started
    command: sh -c "/debezium/run.sh"

  flink-jobmanager:
    image: flink:1.13.2-scala_2.12
    ports:
      - "12081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager

  flink-taskmanager:
    image: flink:1.13.2-scala_2.12
    depends_on:
      - flink-jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 2

  flink-sql-client:
    image: thekingofcity/pravega-cdc-demo-flink-sql-client:0.1
    depends_on:
      - flink-jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
